function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 21-May-2021 21:54:10

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 6, ...
    'Length', 2, ...
    'Width', 2, ...
    'Height', 0.05, ...
    'Name', 'Drone');
waypoints = [0 0 0;
    20.4 -0.1 0;
    20.7 19.6 0;
    0.4 19.9 0;
    0.4 49.2 0;
    -5.3 52.4 0;
    -6.8 56.4 0;
    -7.3 63.2 0;
    -6.3 65.9 0;
    -4.6 68.9 0;
    -2.3 70.7 0;
    2.7 71.4 0;
    7.4 71.4 0;
    9.7 69.9 0;
    10.4 66.2 0;
    9.9 58.4 0;
    7.4 54.7 0;
    2.4 50.4 0;
    -1.8 47.9 0;
    -1.8 19.9 0;
    -20.4 19.4 0;
    -20.1 -0.1 0;
    0 -0.1 0];
speed = [6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6;6];
trajectory(egoVehicle, waypoints, speed);

